Major rewrite of promise support
juliengirault/wikimedia-mapdata pull request #1
Opened 2016-10-11 03:52 UTC by nyurik

2016-10-11 03:53 UTC, nyurik commented
I think we should really switch to spaces after this - I cannot stand tabs in code, makes it much harder to edit

2016-10-11 13:35 UTC, juliengirault requested changes

2016-10-11 13:35 UTC, juliengirault commented on src/DataLoader.js
> +				if ( promise.mwResolve ) {
You're using `mwResolve` here but  `wmResolve` in `fetchGroup`

2016-10-11 13:35 UTC, juliengirault commented on src/DataLoader.js
> +		// http://stackoverflow.com/questions/39970101/combine-multiple-debounce-promises-in-js
👍

2016-10-11 13:38 UTC, juliengirault commented
Agree, we should override [validateIndentation](http://jscs.info/rule/validateIndentation) in `.jscsrc`.

2016-10-11 14:17 UTC, nyurik commented on src/DataLoader.js
> +				if ( promise.mwResolve ) {
thx, fixed

2016-10-19 20:58 UTC, juliengirault commented
Thanks !

2016-10-19 20:58 UTC, merged